import type { CropDefinition, ModelDefinition, ModelId } from './game-types';

const MINUTE = 60_000;

export const MODELS: readonly ModelDefinition[] = [
  {
    id: 'gpt-5.4-mini',
    label: 'GPT-5.4 Mini',
    shortLabel: '5.4 Mini',
    color: '#2f9d77',
    bloom: 'star',
  },
  { id: 'gpt-5.4', label: 'GPT-5.4', shortLabel: 'GPT-5.4', color: '#216e63', bloom: 'star' },
  {
    id: 'claude-sonnet-4-6',
    label: 'Claude Sonnet 4.6',
    shortLabel: 'Sonnet',
    color: '#d56a4a',
    bloom: 'round',
  },
  {
    id: 'claude-opus-4-8',
    label: 'Claude Opus 4.8',
    shortLabel: 'Opus 4.8',
    color: '#7d65a9',
    bloom: 'double',
  },
  {
    id: 'claude-fable-5',
    label: 'Claude Fable 5',
    shortLabel: 'Fable 5',
    color: '#c85c66',
    bloom: 'round',
  },
  {
    id: 'claude-haiku-4-5',
    label: 'Claude Haiku 4.5',
    shortLabel: 'Haiku',
    color: '#e58c58',
    bloom: 'round',
  },
  {
    id: 'claude-haiku-4-5-20251001',
    label: 'Claude Haiku 4.5 Oct',
    shortLabel: 'Haiku Oct',
    color: '#d7784d',
    bloom: 'double',
  },
  {
    id: 'claude-opus-4-6',
    label: 'Claude Opus 4.6',
    shortLabel: 'Opus 4.6',
    color: '#8b68a8',
    bloom: 'double',
  },
  {
    id: 'claude-opus-4-7',
    label: 'Claude Opus 4.7',
    shortLabel: 'Opus 4.7',
    color: '#745a9d',
    bloom: 'double',
  },
  {
    id: 'claude-sonnet-5',
    label: 'Claude Sonnet 5',
    shortLabel: 'Sonnet 5',
    color: '#b94e5f',
    bloom: 'round',
  },
  {
    id: 'deepseek-v4-flash',
    label: 'DeepSeek V4 Flash',
    shortLabel: 'DS Flash',
    color: '#287fb8',
    bloom: 'lotus',
  },
  {
    id: 'deepseek-v4-pro',
    label: 'DeepSeek V4 Pro',
    shortLabel: 'DS Pro',
    color: '#1f5e9d',
    bloom: 'lotus',
  },
  {
    id: 'gemini-3.1-pro-preview',
    label: 'Gemini 3.1 Pro',
    shortLabel: 'Gemini Pro',
    color: '#397bd7',
    bloom: 'double',
  },
  {
    id: 'gemini-3.5-flash',
    label: 'Gemini 3.5 Flash',
    shortLabel: 'Gemini',
    color: '#d2a53b',
    bloom: 'star',
  },
  { id: 'glm-5.2', label: 'GLM 5.2', shortLabel: 'GLM 5.2', color: '#45a990', bloom: 'crystal' },
  { id: 'gpt-5.5', label: 'GPT-5.5', shortLabel: 'GPT-5.5', color: '#23876f', bloom: 'star' },
  {
    id: 'gpt-5.6-luna',
    label: 'GPT-5.6 Luna',
    shortLabel: 'Luna',
    color: '#6474bd',
    bloom: 'crystal',
  },
  { id: 'gpt-5.6-sol', label: 'GPT-5.6 Sol', shortLabel: 'Sol', color: '#d29d31', bloom: 'star' },
  {
    id: 'gpt-5.6-terra',
    label: 'GPT-5.6 Terra',
    shortLabel: 'Terra',
    color: '#638749',
    bloom: 'lotus',
  },
  {
    id: 'gpt-image-2',
    label: 'GPT Image 2',
    shortLabel: 'Image 2',
    color: '#c45191',
    bloom: 'double',
  },
] as const;

export const FEATURED_MODELS = MODELS.slice(0, 4);

export const CROPS: readonly CropDefinition[] = [
  {
    id: 'starter-bloom',
    level: 0,
    name: '新手数据花',
    cost: 0n,
    baseReward: 100n,
    fruitCount: 1,
    durationMs: MINUTE,
    color: '#f3d96b',
    accent: '#54a16e',
  },
  {
    id: 'radish',
    level: 1,
    name: '白萝卜',
    cost: 10_000n,
    fruitCount: 5,
    durationMs: MINUTE,
    color: '#eef0d8',
    accent: '#70aa58',
  },
  {
    id: 'carrot',
    level: 2,
    name: '胡萝卜',
    cost: 20_000n,
    fruitCount: 10,
    durationMs: 2 * MINUTE,
    color: '#f28b38',
    accent: '#5e9c4c',
  },
  {
    id: 'cabbage',
    level: 3,
    name: '大白菜',
    cost: 50_000n,
    fruitCount: 20,
    durationMs: 5 * MINUTE,
    color: '#b8d46c',
    accent: '#567c42',
  },
  {
    id: 'garlic',
    level: 4,
    name: '大蒜',
    cost: 100_000n,
    fruitCount: 20,
    durationMs: 10 * MINUTE,
    color: '#e9dfbc',
    accent: '#78a858',
  },
  {
    id: 'scallion',
    level: 5,
    name: '大葱',
    cost: 210_000n,
    fruitCount: 30,
    durationMs: 20 * MINUTE,
    color: '#cce59d',
    accent: '#4d8c50',
  },
  {
    id: 'rice',
    level: 6,
    name: '水稻',
    cost: 420_000n,
    fruitCount: 30,
    durationMs: 40 * MINUTE,
    color: '#e4c857',
    accent: '#4b8b4a',
  },
  {
    id: 'wheat',
    level: 7,
    name: '小麦',
    cost: 630_000n,
    fruitCount: 40,
    durationMs: 60 * MINUTE,
    color: '#e0ad3c',
    accent: '#6e8c41',
  },
  {
    id: 'corn',
    level: 8,
    name: '玉米',
    cost: 840_000n,
    fruitCount: 40,
    durationMs: 80 * MINUTE,
    color: '#ffd34e',
    accent: '#4f8740',
  },
  {
    id: 'ginger',
    level: 9,
    name: '鲜姜',
    cost: 1_110_000n,
    fruitCount: 60,
    durationMs: 100 * MINUTE,
    color: '#c99758',
    accent: '#608847',
  },
  {
    id: 'potato',
    level: 10,
    name: '土豆',
    cost: 1_340_000n,
    fruitCount: 60,
    durationMs: 120 * MINUTE,
    color: '#ae8153',
    accent: '#668f4d',
  },
  {
    id: 'bok-choy',
    level: 11,
    name: '小白菜',
    cost: 1_670_000n,
    fruitCount: 80,
    durationMs: 150 * MINUTE,
    color: '#9bcf67',
    accent: '#3f7d43',
  },
  {
    id: 'lettuce',
    level: 12,
    name: '生菜',
    cost: 2_010_000n,
    fruitCount: 80,
    durationMs: 180 * MINUTE,
    color: '#7fc96b',
    accent: '#356f42',
  },
  {
    id: 'rapeseed',
    level: 13,
    name: '油菜花',
    cost: 2_880_000n,
    fruitCount: 200,
    durationMs: 240 * MINUTE,
    color: '#f5d849',
    accent: '#4a8744',
  },
  {
    id: 'eggplant',
    level: 14,
    name: '茄子',
    cost: 5_760_000n,
    fruitCount: 200,
    durationMs: 480 * MINUTE,
    color: '#7951a1',
    accent: '#4e8546',
  },
  {
    id: 'jujube',
    level: 15,
    name: '红枣',
    cost: 8_640_000n,
    fruitCount: 200,
    durationMs: 720 * MINUTE,
    color: '#c4493d',
    accent: '#507f43',
  },
] as const;

export const WELCOME_BALANCE = 80_000n;

export function getCrop(cropId: string | null): CropDefinition | undefined {
  return CROPS.find((crop) => crop.id === cropId);
}

export function getModel(modelId: ModelId): ModelDefinition {
  return MODELS.find((model) => model.id === modelId) ?? MODELS[0];
}
